name: build-linux-x86

on:
  push:
    branches:
      - "*"

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: dontcare

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Info
        run: npx envinfo
      - name: Build
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install g++-multilib gcc-multilib libstdc++6:i386 libc6:i386
          ./configure --shared --dest-cpu=ia32 --openssl-no-asm && make -j8
      - name: Build
        run: |
          cd out/Release
          ls
      - name: Upload libnode.so.108 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode.so.108
          path: out/Release/libnode.so.108
