name: build-linux-x64

on:
  push:
    branches:
      - "*"

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: dontcare

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Environment Info
        run: npx envinfo
      - name: Build
        run: |
          cd docker
          cd ubuntu_18.04-x64
          chmod +x ./build.sh
          chmod +x ./docker-entrypoint.sh
          ./build.sh
      - name: Upload libnode.so.108 artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode.so.108-x64
          path: docker/ubuntu_18.04-x64/out/Release/libnode.so.108
