name: Build from tarball

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '.mailmap'
      - '**.md'
      - 'AUTHORS'
      - 'doc/**'
      - .github/**
      - '!.github/workflows/build-tarball.yml'
  push:
    branches:
      - master
      - main
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - '.mailmap'
      - '**.md'
      - 'AUTHORS'
      - 'doc/**'
      - .github/**
      - '!.github/workflows/build-tarball.yml'

env:
  FLAKY_TESTS: dontcare

jobs:
  build-tarball:
    if: github.event.pull_request.draft == false
    env:
      PYTHON_VERSION: '3.10'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Info
        run: npx envinfo
      - name: Make tarball
        run: |
          export DISTTYPE=nightly
          export DATESTRING=`date "+%Y-%m-%d"`
          export COMMIT=$(git rev-parse --short=10 "$GITHUB_SHA")
          ./configure --shared && make tar -j8 SKIP_XZ=1
          mkdir tarballs
          mv *.tar.gz tarballs
      - name: Upload tarball artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarballs
          path: tarballs
