name: Build from tarball

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  build-tarball:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Make tarball
        run: |
          export DISTTYPE=nightly
          export DATESTRING=`date "+%Y-%m-%d"`
          export COMMIT=$(git rev-parse --short=10 "$GITHUB_SHA")
          ./configure --fully-static --shared && make tar -j8 SKIP_XZ=1
          mkdir tarballs
          mv *.tar.gz tarballs
      - name: Upload tarball artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.3.3
        with:
          name: tarballs
          path: tarballs
