name: Build Windows

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - README.md

env:
  PYTHON_VERSION: '3.12'
  FLAKY_TESTS: keep_retrying

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d  # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat release dll static x64
      - name: Copy  and compress files
        shell: bash
        run: |
          mkdir bin
          cp out/Release/libnode.dll ./bin/libnode.dll
          cp out/Release/libnode.lib ./bin/libnode.lib
          powershell -NoLogo -NoProfile -Command Compress-Archive -DestinationPath "Release.zip" -Path "bin"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.zip
            ./bin/libnode.dll
            ./bin/libnode.lib
