name: build-windows-debug

on:
  push:
    branches:
      - "*"

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: dontcare

jobs:
  build-windows-debug:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Info
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat debug dll
      - name: Upload libnode.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode.dll
          path: out/Debug/libnode.dll
      - name: Upload libnode.pdb artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode.pdb
          path: out/Debug/libnode.pdb
      - name: Upload libnode.lib artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnode.lib
          path: out/Debug/libnode.lib
